version: '2'
services:
  postgresql:
    image: postgres:11-alpine
    container_name: portfolio_postgresql
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  backend:
    image: couclock/portfolio_backend
    container_name: portfolio_backend
    ports:
      - '8080:8080'
    depends_on:
      - postgresql

  frontend:
    image: couclock/portfolio_frontend
    container_name: portfolio_frontend
    build: ./front/docker
    ports:
      - '80:80'
    depends_on:
      - backend
